name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    branches: [ main ]
    branches: [ main ]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: CyberSecurityApp-release
          path: app/build/outputs/apk/release/*.apk
