name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

# cancel build lama kalau ada push baru di branch yang sama
concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle (install Gradle on runner)
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.5'

    - name: Grant execute permission for gradlew (if present)
      run: |
        if [ -f "./gradlew" ]; then chmod +x ./gradlew; fi

    - name: Build (use installed gradle)
      run: gradle --no-daemon --console=plain --stacktrace assembleDebug

    - name: Upload APK (artifact v4)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        compression-level: 5
