name: Android Release CI/CD Final+

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Grant permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Move APK to Build folder
        run: |
          mkdir -p Build
          cp -r app/build/outputs/apk/release/*.apk Build/ || echo "APK not found!"

      - name: Upload artifact (build result)
        uses: actions/upload-artifact@v4
        with:
          name: CyberSecurityApp-Release
          path: Build/*.apk

      - name: Create GitHub Release (auto tag)
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: v${{ github.run_number }}
          name: CyberSecurityApp v${{ github.run_number }}
          files: Build/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save logs on failure
        if: failure()
        run: |
          mkdir -p logs
          echo "Build failed at $(date)" > logs/build_failed_$(date +%Y%m%d_%H%M%S).txt
          ./gradlew --stacktrace >> logs/build_failed_$(date +%Y%m%d_%H%M%S).txt || true
