name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Clean Gradle cache & build dirs
        run: |
          rm -rf .gradle/ app/build/ build/ || true

      - name: Generate .gitignore and .gitattributes
        run: |
          cat > .gitignore << 'EOF'
          # Gradle
          .gradle/
          build/
          */build/
          local.properties

          # Android Studio
          .idea/
          *.iml

          # Logs & temp
          *.log
          *.tmp
          *.bak

          # APK / keystore
          *.apk
          *.ap_
          *.keystore
          *.jks

          # Backup manifest
          app/src/main/AndroidManifest.xml.bak*
          EOF

          cat > .gitattributes << 'EOF'
          * text=auto eol=lf

          *.java text diff=java
          *.kt   text diff=kotlin
          *.xml  text diff=xml
          *.yml  text diff=yaml
          *.gradle text diff=java
          *.sh   text eol=lf

          *.properties text
          *.md text diff=markdown
          *.gitignore text
          *.gitattributes text

          *.log -diff
          *.err -diff
          *.out -diff
          *.tmp -diff
          *.bak -diff

          *.jar binary
          *.keystore binary
          *.jks binary
          *.png binary
          *.jpg binary
          *.jpeg binary
          *.gif binary
          *.webp binary
          *.mp4 binary
          *.so binary
          EOF

      - name: Commit generated ignore files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .gitignore .gitattributes || true
          git commit -m "chore: update .gitignore & .gitattributes [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/} || echo "No push needed"

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
