name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace | tee build_debug.log | grep -iE "error|failed|failure" || true

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace | tee build_release.log | grep -iE "error|failed|failure" || true

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: APKs
        path: app/build/outputs/apk/**/*.apk

    - name: Upload Debug Build Log
      uses: actions/upload-artifact@v4
      with:
        name: debug-log
        path: build_debug.log

    - name: Upload Release Build Log
      uses: actions/upload-artifact@v4
      with:
        name: release-log
        path: build_release.log
